package com.connect.professional.user.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
@DynamoDBTable(tableName = "user")
public class User {
    @DynamoDBHashKey
    private String partitionKey;
    @DynamoDBAutoGeneratedKey
    private String id;
    @DynamoDBAttribute
    private String username;
    @DynamoDBAttribute
    private String password;
    @DynamoDBAttribute
    private String email;
    @DynamoDBAttribute
    private String fullName;

    public String getPartitionKey() {
        return "USER#" + username;
    }
}
